@startuml
class TrueFalseQuestion {
    + <<override>> GetRandomAnswer() : List<string>
    + <<override>> GetSubmissionPoint(submissionCopy:List<string>, indent:int) : float
}
Question <|-- TrueFalseQuestion
@enduml
